In [1]:
import tensorflow as tf
import numpy as np
import pprint

tf.random.set_seed(777)
pp = pprint.PrettyPrinter(indent=4)

# Simple Array
t = np.array([0., 1., 2., 3., 4., 5., 6.])
pp.pprint(t)
print(t.ndim)      # rank
print(t.shape)     # shape
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

# 2D Array
t = np.array([[1., 2., 3.],
              [4., 5., 6.],
              [7., 8., 9.],
              [10., 11., 12.]])
pp.pprint(t)
print(t.ndim)
print(t.shape)

# Shape, Rank, Axis
t = tf.constant([1,2,3,4])
print(tf.shape(t).numpy())

t = tf.constant([[1,2],[3,4]])
print(tf.shape(t).numpy())

t = tf.constant(
    [
        [
            [
                [1,2,3,4], [5,6,7,8], [9,10,11,12]
            ],
            [
                [13,14,15,16],[17,18,19,20],[21,22,23,24]
            ]
        ]
    ]
)
print(tf.shape(t).numpy())

# Matmul vs Multiply
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
print(tf.matmul(matrix1, matrix2).numpy())
print((matrix1 * matrix2).numpy())

# Broadcasting
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
print((matrix1 + matrix2).numpy())

matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2., 2.]])
print((matrix1 + matrix2).numpy())

# Random values
print(tf.random.normal([3]).numpy())
print(tf.random.uniform([2]).numpy())
print(tf.random.uniform([2, 3]).numpy())

# Reduce Mean/Sum
print(tf.reduce_mean([1, 2], axis=0).numpy())

x = [[1., 2.],
     [3., 4.]]

print(tf.reduce_mean(x).numpy())
print(tf.reduce_mean(x, axis=0).numpy())


array([0., 1., 2., 3., 4., 5., 6.])
1
(7,)
0.0 1.0 6.0
[2. 3. 4.] [4. 5.]
[0. 1.] [3. 4. 5. 6.]
array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])
2
(4, 3)
[4]
[2 2]
[1 2 3 4]
[[12.]]
[[6. 6.]
 [6. 6.]]
[[5. 5.]
 [5. 5.]]
[[5. 5.]]
[ 0.7706481   0.37335402 -0.05576323]
[0.42134905 0.7339295 ]
[[0.909613   0.34968376 0.39626384]
 [0.6574153  0.60619414 0.70691717]]
1
2.5
[2. 3.]
